### ISSUE TITLE
failing inside a container

### ISSUE THREAD

**Issue by Goldziher** [furstenheim/babel-plugin-meaningful-logs#3] opened 2019-08-11 15:43 UTC
Thanks for the great plugin! I'm unable to use the plugin inside docker. All works well when I try outside docker-

babel.config.js:

`if (api.env(['development', 'debug']))
		plugins.push(['meaningful-logs', { maxDepth: 3 }])
`

But when I run my webpack devserver inside a container I get this:

`Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'start' of undefined
    at PluginPass.CallExpression (/var/www/yoda/node_modules/babel-plugin-meaningful-logs/dist/index.js:37:41)
    at newFn (/var/www/yoda/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/var/www/yoda/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/var/www/yoda/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/var/www/yoda/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/var/www/yoda/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/var/www/yoda/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/var/www/yoda/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/var/www/yoda/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/var/www/yoda/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/var/www/yoda/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/var/www/yoda/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/var/www/yoda/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/var/www/yoda/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/var/www/yoda/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/var/www/yoda/node_modules/@babel/traverse/lib/context.js:118:16)`

**Comment by furstenheim** [comment] 2019-08-12 16:31
That is interesting, since that would mean that babel api is changing inside a container. The offending line is:
```    
let line = expression.loc.start.line;
```

Could you provide a minimal example that reproduces the problem? Including the docker file

**Comment by furstenheim** [comment] 2019-09-06 19:05
I'll close it for now. Feel free to open it again with a reproducible code.

**Closed by furstenheim** 2019-09-06 19:05 UTC
